# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1bcb775cde4e037cb74bb21b91d374cf8fe1e96b8a15289fe9fe1956abdd5e30269dc7be86fd4c20451d2e25ba80fb391296acdba46bcbfc65b2aaaf41f8ca3

test:
  secret_key_base: 8692efd1421330c58ecdd4dc264c04eae1b3abc33cb17b316b2e982ed4dc3064f0f08266a3c4f5e91546648ff6460d996efe35e0383f29c97d2efea63474d5ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
